### ISSUE TITLE
Enhancements ideas (take this with a grain of salt)

### ISSUE THREAD

**Issue by gcrozariol** [marcelluscaio/game-marketplace#13]
Here are some enhancement ideas from my perspective, but like I said in the title: take this with a grain of salt, as each developer and each company has its way of doing things.

**`.env` file:** 
-  You could reference the `POSTGRES_USER`, `POSTGRES_PASWORD`, and `POSTGRES_DB` variables within the `DATABASE_URL` variable.
- For instance: 
  - Instead of `postgresql://[POSTGRES_USER]:[POSTGRES_PASSWORD]@localhost:5432/[POSTGRES_DB]?schema=public`;
  - You could use `postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?schema=public`
  - This way, you have less chance of human error.

**`package.json` file:**

- I would add some scripts to deal with Prisma stuff easily. For instance: 
  - prisma:migrate
  - prisma:seed
  - prisma:rollback

**Project structure overview:** 

- The `libs` folder usually contains all libs used in the project. I see the `dayjs` lib being exported but with no extra configurations. Personally, I would only export libs if I have a custom setup for that lib. In your case, there's no extra config, so I wouldn't create an extra file on the project to export a lib that will continue to work the default way. 

- The `View` folder seems a bit unnecessary as Next.js has its own way of implementing views. It's not a huge problem, but this can lead to architecture issues down the road when the app grows and the team grows too.

- Usually, when you have components that are used within a page, you create a `components` folder for that page to either: 
  - Separate your logic when the view is too complex, or;
  - Separate your components because you will reuse them
  - If your case does not fit in at least one of the two cases above, then there's no need to separate components as your project structure will be bigger with no real benefits.

**Final remarks:** 

- Overall, the project works, which is a great thing lol
- Be mindful of long coding challenges; you can show your skills with personal and professional projects
- Keep coding and keep practicing. Considering the time you've been coding, this is an excellent result!

Cheers 🍻

**Comment by marcelluscaio** [comment]
Thank you very much, mate!

I've implemented the env and package.json suggestions. That was a great addition to the project.

o/
